import { environment } from './../../environments/environment';
export class Resource {
    static readonly RESOURCE_SERVER_ROOT_URL = environment.resourceServer;
    static readonly GET_APPLICANTS_URL = Resource.RESOURCE_SERVER_ROOT_URL + 'family/ApplicantList';
    static readonly GET_FAMILY_URL = Resource.RESOURCE_SERVER_ROOT_URL + 'family/';
    static readonly GET_SPONSORSHIP_REQUEST = Resource.RESOURCE_SERVER_ROOT_URL + 'rcoRequest/';
    static readonly GET_SPONSORSHIP_REQUEST_BY_FAMILY_ID = Resource.RESOURCE_SERVER_ROOT_URL + 'rcoRequest/family/';
    static readonly GET_SPONSORSHIP_CHANGE_REQUEST = Resource.RESOURCE_SERVER_ROOT_URL + 'rcoChangeRequest/beneficiary/';
    static readonly SAVE_SPONSORSHIP_CHANGE_REQUEST = Resource.RESOURCE_SERVER_ROOT_URL + 'rcoChangeRequest/';
    static readonly POST_SPONSORSHIP_CHANGE_REQUEST = Resource.RESOURCE_SERVER_ROOT_URL + 'rcoChangeRequest/';
    static readonly SAVE_SPONSORSHIP_REQUEST = Resource.RESOURCE_SERVER_ROOT_URL + 'rcoRequest/';
    static readonly POST_SPONSORSHIP_REQUEST = Resource.RESOURCE_SERVER_ROOT_URL + 'rcoRequest/';
    static readonly VALIDATE_PARENTS_MARRIAGE_RELATIONSHIP =
        Resource.RESOURCE_SERVER_ROOT_URL + 'rcoRequest/validate/{fatherCpr}/{motherCpr}';
    static readonly GET_PERSON_URL = Resource.RESOURCE_SERVER_ROOT_URL + 'person/';
    static readonly GET_LOOKUP_URL = Resource.RESOURCE_SERVER_ROOT_URL + 'admin';
    static readonly GET_MARITAL_STATUS = Resource.RESOURCE_SERVER_ROOT_URL + 'family/LastMarriage/';
    static readonly GET_HAVE_CHILDERN = Resource.RESOURCE_SERVER_ROOT_URL + 'family/ChildrenBySpouse/';
    static readonly GET_ATTACHMENT_LIST = Resource.RESOURCE_SERVER_ROOT_URL + 'attachment/list/';
    static readonly GET_ATTACHMENT_FILE = Resource.RESOURCE_SERVER_ROOT_URL + 'attachment/get?id=';
    static readonly DELETE_ATTACHMENT = Resource.RESOURCE_SERVER_ROOT_URL + 'attachment/delete/?id=';
    static readonly ATTACHMENT_UPLOAD_URL = Resource.RESOURCE_SERVER_ROOT_URL + 'attachment/?attachmentTypeId=';
    static readonly GET_INCOME_ATTACHMENT_URL = Resource.RESOURCE_SERVER_ROOT_URL + 'attachment/income/get?id=';
    static readonly GET_EXPENSE_ATTACHMENT_URL = Resource.RESOURCE_SERVER_ROOT_URL + 'attachment/expense/get?id=';
    static readonly UPLOAD_INCOME_ATTACHMENT_URL = Resource.RESOURCE_SERVER_ROOT_URL + 'attachment/income/add';
    static readonly UPLOAD_EXPENSE_ATTACHMENT_URL = Resource.RESOURCE_SERVER_ROOT_URL + 'attachment/expense/add';
    static readonly DELETE_INCOME_ATTACHMENT_URL = Resource.RESOURCE_SERVER_ROOT_URL + 'attachment/income/delete/?incomeId=';
    static readonly DELETE_INCOME_URL = Resource.RESOURCE_SERVER_ROOT_URL + 'income/delete/?incomeId=';
    static readonly GET_USER_DETAILS = Resource.RESOURCE_SERVER_ROOT_URL + 'user';
    static readonly CHECK_TOKEN_VALIDITY = Resource.RESOURCE_SERVER_ROOT_URL + 'oauth/check_token?token=';
    static readonly GET_BENEFICIARY_PAYMENT_URL = Resource.RESOURCE_SERVER_ROOT_URL + 'BeneficiaryPayment?cpr=';
    static readonly POST_ACCOUNT_URL = Resource.RESOURCE_SERVER_ROOT_URL + 'account';
    static readonly POST_SPONSER_URL = Resource.RESOURCE_SERVER_ROOT_URL + 'sponser';
    static readonly GET_QUESTION_URL = Resource.RESOURCE_SERVER_ROOT_URL + 'visitDetail/question';
    static readonly GET_ANSWERS_URL = Resource.RESOURCE_SERVER_ROOT_URL + 'visitDetail/answer/';
    static readonly SAVE_VISIT_DETAILS = Resource.RESOURCE_SERVER_ROOT_URL + 'visitDetail/answer/?visitId=';
    static readonly SEARCH_USER_TASKS = Resource.RESOURCE_SERVER_ROOT_URL + 'task/search';
    static readonly GET_SPONSORSHIP_REQUEST_BY_ID = Resource.RESOURCE_SERVER_ROOT_URL + 'rcoRequest/';
    static readonly GET_MEETING_URL = Resource.RESOURCE_SERVER_ROOT_URL + 'committee/meeting/';
    static readonly GET_MEETING_MEMBER_URL = Resource.RESOURCE_SERVER_ROOT_URL + 'committee/member';
    static readonly GET_RESEARCHER_VISITS_BY_FAMILY_ID = Resource.RESOURCE_SERVER_ROOT_URL + 'visit?familyId=';
    static readonly GET_ASSIGNEES_URL = Resource.RESOURCE_SERVER_ROOT_URL + 'assignee';
    static readonly GET_PERSON_ADDRESS = Resource.RESOURCE_SERVER_ROOT_URL + 'visit/address?cpr=';
    static readonly ADD_RESEARCHER_VISIT = Resource.RESOURCE_SERVER_ROOT_URL + 'visit';
    static readonly GET_USER_TASKS = Resource.RESOURCE_SERVER_ROOT_URL + 'task';
    static readonly POST_MEETING_URL = Resource.RESOURCE_SERVER_ROOT_URL + 'committee/meeting/';
    static readonly POST_MEETING_MEMBERS_URL = Resource.RESOURCE_SERVER_ROOT_URL + 'committee/meeting/{id}/member';
    static readonly GET_MEETING_TASKS_URL = Resource.RESOURCE_SERVER_ROOT_URL + 'committee/meeting/{id}/tasks';
    static readonly POST_UPDATE_MEETING_URL = Resource.RESOURCE_SERVER_ROOT_URL + 'committee/meeting/update/';
    static readonly PUT_END_COMMITTEE_MEETING=Resource.RESOURCE_SERVER_ROOT_URL +'committee/meeting/{id}';
    static readonly GET_RESEARCHER_VISIT_ATTACHMENTS_LIST_URL = Resource.RESOURCE_SERVER_ROOT_URL + 'attachment/visit/get/list?visitId=';
    static readonly GET_RESEARCHER_VISIT_ATTACHMENT_URL = Resource.RESOURCE_SERVER_ROOT_URL + 'attachment/visit/get?id=';
    static readonly DELETE_RESEARCHER_VISIT_ATTACHMENT_URL = Resource.RESOURCE_SERVER_ROOT_URL + 'attachment/visit/delete?attachmentId=';
    static readonly UPLOAD_RESEARCHER_VISIT_ATTACHMENT_URL = Resource.RESOURCE_SERVER_ROOT_URL + 'attachment/visit/add';
    static readonly UPDATE_RESEARCHER_VISIT_SCHEDULE = Resource.RESOURCE_SERVER_ROOT_URL + 'visit';
    static readonly DELETE_RESEARCHER_VISIT_URL = Resource.RESOURCE_SERVER_ROOT_URL + 'visit?visitId=';
    static readonly GET_CASHING_LIST_URL = Resource.RESOURCE_SERVER_ROOT_URL + 'report/cashingReport?month=';
    static readonly GET_MONTHLY_DIFFERENCES_LIST_URL = Resource.RESOURCE_SERVER_ROOT_URL + 'report/differencesReport?firstMonth=';
    static readonly GET_CR_RESEARCHER_VISITS_BY_FAMILY_ID = Resource.RESOURCE_SERVER_ROOT_URL + 'visit/changeRequest?familyId=';
    static readonly ADD_CR_RESEARCHER_VISIT = Resource.RESOURCE_SERVER_ROOT_URL + 'visit/changeRequest';
    static readonly UPDATE_CR_RESEARCHER_VISIT_SCHEDULE = Resource.RESOURCE_SERVER_ROOT_URL + 'visit/changeRequest';
    static readonly DELETE_CR_RESEARCHER_VISIT_URL = Resource.RESOURCE_SERVER_ROOT_URL + 'visit/changeRequest?visitId=';
    static readonly GET_CR_RESEARCHER_VISIT_ATTACHMENTS_LIST_URL = Resource.RESOURCE_SERVER_ROOT_URL + 'attachment/visit/get/list/changeRequest?visitId=';
    static readonly GET_CR_RESEARCHER_VISIT_ATTACHMENT_URL = Resource.RESOURCE_SERVER_ROOT_URL + 'attachment/visit/get/changeRequest?id=';
    static readonly DELETE_CR_RESEARCHER_VISIT_ATTACHMENT_URL = Resource.RESOURCE_SERVER_ROOT_URL + 'attachment/visit/delete/changeRequest?attachmentId=';
    static readonly UPLOAD_CR_RESEARCHER_VISIT_ATTACHMENT_URL = Resource.RESOURCE_SERVER_ROOT_URL + 'attachment/visit/add/changeRequest';
}
